### ISSUE TITLE
January Iteration Plan

### ISSUE THREAD

**Issue by camwest** [orion-ui/orion#38]
# Plan Items

## Themes

* release first component

### Button Component
  * [x] Add size attribute https://github.com/orion-ui/orion/issues/31
  * [x] Add background color attribute https://github.com/orion-ui/orion/issues/32
  * [x] Add disabled attribute https://github.com/orion-ui/orion/issues/33
  * [x] React adapter for Button https://github.com/orion-ui/orion/issues/17
  * [x] Document button component in storybook https://github.com/orion-ui/orion/issues/41

### Select Menu Component

* [x] Create specs for select menu https://github.com/orion-ui/orion/issues/42

## Engineering

* [x] Add code quality reports to pull requests https://github.com/orion-ui/orion/issues/24
* [x] Explore visual testing of html components https://github.com/orion-ui/orion/issues/28

## Documentation

The remainder has been moved to https://github.com/orion-ui/orion/issues/56
