### ISSUE TITLE
December Iteration Plan

### ISSUE THREAD

**Issue by camwest** [orion-ui/orion#7]
# Plan Items

## Themes

* getting set up
* release first component

## Components

* [ ] Create wireframe for Select component
* [ ] React adapter for Button https://github.com/orion-ui/orion/issues/17
* [ ] Angular adapter for Button https://github.com/orion-ui/orion/issues/34
* [ ] Finalize Button component
  * [ ] Add size attribute https://github.com/orion-ui/orion/issues/31
  * [ ] Add background color attribute https://github.com/orion-ui/orion/issues/32
  * [ ] Add disabled attribute https://github.com/orion-ui/orion/issues/33

## Engineering

* [x] Linting runs on PR https://github.com/orion-ui/orion/issues/9
* [x] Run all unit tests on PR https://github.com/orion-ui/orion/issues/10
* [ ] Setup S3 and CloudFront for snapshots https://github.com/orion-ui/orion/issues/16
* [x] Add high level tests for checking for copyright https://github.com/orion-ui/orion/issues/23
* [ ] Add code quality reports to pull requests https://github.com/orion-ui/orion/issues/24
* [ ] Explore visual testing of html components https://github.com/orion-ui/orion/issues/28
* [ ] Run NPM deploy on PR if user is in whitelist
* [ ] Convert existing code to TypeScript 2.0
* [ ] Add commit message format & validation

## Documentation

* [x] Setup `react-storybook` in new package https://github.com/orion-ui/orion/issues/8
* [x] Add knobs addon to react-storybook https://github.com/orion-ui/orion/issues/11
* [x] Create SourceViewer component in react-storybook https://github.com/orion-ui/orion/issues/12
* [ ] Sketch for how release notes will look
